dominodatalab/hephaestus

deployments/crds/hephaestus.dominodatalab.com_imagebuilds.yaml, deployments/helm/hephaestus/values.yaml, go.mod, go.sum, pkg/api/hephaestus/v1/imagebuild_types.go, pkg/buildkit/buildkit.go, pkg/controller/imagebuild/component/builddispatcher.go, pkg/controller/imagebuild/component/deletebroadcaster.go, pkg/controller/imagebuild/imagebuild.go, pkg/controller/imagebuild/predicate/predicate.go, pkg/controller/start.go
- separate context handling when build a new buildkit client and calling `Solve` on that client
- adds `DeleteBroadcaster` to watch for and emit messages when image build resources are deleted
- `BuildDispatcher` listens for and acts upon delete broadcasts to cancel buildkit `Solve` contexts.
=> Cancel buildkitd Solve on ImageBuild delete

deployments/helm/hephaestus/templates/controller/deployment.yaml, deployments/helm/hephaestus/templates/controller/secret.yaml, deployments/helm/hephaestus/values.yaml, pkg/buildkit/buildkit.go, pkg/config/config.go, pkg/controller/imagebuild/component/builddispatcher.go, pkg/controller/imagebuild/imagebuild.go
e.g.
```yaml
controller:
extraVolumes:
- name: cert-vol
configMap:
name: domino-generated-certificates
extraVolumeMounts:
- name: cert-vol
mountPath: /certs
secrets:
cacerts.p12: "/certs/cacerts.p12"
ca-certificates.crt: "/certs/ca-certificates.crt"
```
and referencing them:
```dockerfile
FROM ...
RUN --mount=type=secret,required=true,target=/etc/ssl/certs/ca-certificates.crt,mode=444 \
--mount=type=secret,required=true,target=/etc/ssl/certs/cacerts.p12,mode=444 \
ls -la /etc/ssl/certs/
```
=> allowing providing secrets to hephaestus to pass to builds

api/api-rules/violation_exceptions.list, api/openapi-spec/swagger.json, deployments/helm/hephaestus/templates/certificates.yaml, deployments/helm/hephaestus/templates/controller/deployment.yaml, deployments/helm/hephaestus/templates/controller/secret.yaml, pkg/api/hephaestus/v1/zz_generated.openapi.go, pkg/config/config.go, pkg/controller/imagebuild/component/builddispatcher.go, scripts/sdk/generate.sh
Inside the helm chart, when `buildkit.mtls.enabled=false`, buildkit does not use certs for mTLS. This change adds the same behavior to the controller and  does not render the buildkit certificates
=> Removes all traces of buildkit mTLS when disabled

deployments/helm/hephaestus/templates/controller/deployment.yaml, deployments/helm/hephaestus/values.yaml
So that you could hypothetically add volumes and vector configurations to write files into them.
=> Adds logProcessor.extraVolumeMounts value to chart

deployments/helm/hephaestus/templates/_helpers.tpl, deployments/helm/hephaestus/templates/buildkit/configmap.yaml, deployments/helm/hephaestus/templates/buildkit/networkpolicy.yaml, deployments/helm/hephaestus/templates/buildkit/podsecuritypolicy.yaml, deployments/helm/hephaestus/templates/buildkit/service.yaml, deployments/helm/hephaestus/templates/buildkit/serviceaccount.yaml, deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/templates/certificates.yaml, deployments/helm/hephaestus/templates/controller/secret.yaml, deployments/helm/hephaestus/values.yaml
Allows users to deploy controller and buildkit workloads into separate namespaces.
=> Enables multi-namespace helm chart deploy

deployments/helm/hephaestus/templates/controller/deployment.yaml, deployments/helm/hephaestus/values.yaml
users can pass in extra envvars as necessary
=> Adds .Values.controller.extraEnvVars value to helm chart

deployments/helm/hephaestus/templates/buildkit/statefulset.yaml
`labels.standard` include the chart version, which means every upgrade of hephaestus will fail because the PVC template label values are immutable.
=> buildkit: PVC labels are immutable, remove the chart version

pkg/buildkit/worker/pool.go, pkg/buildkit/worker/pool_test.go
- explicitly limits leasing to pods in a _Running_ state to avoid transient state errors (think Istio!)
- adds retry logic to func that queries for buildkit pod Endpoints so that we give k8s enough time to update it
- releases previously-leased pod in the event that we cannot generate an endpoint url
- adds more unit tests for `Pool.Get`
=> Fixes leasing issue in workerPool.Get and adds tests

pkg/buildkit/worker/pool.go, pkg/buildkit/worker/pool_test.go, pkg/buildkit/worker/requestqueue.go, pkg/buildkit/worker/requestqueue_test.go, pkg/controller/imagebuild/component/builddispatcher.go
- Adds `owner` param to `Pool.Get` interface
- Adds `PodRequest` type to carry owner and results channel
- Adds `leased-at` timestamp during lease action
- `PodRequestResult` now carries an address instead of a pod
- Stores owner name in pod's lease metadata
- Now leases/builds endpoint/releases in the event of a failures in sequence w/o channels
=> Adds the ability to track "lease owner" in pod metadata

pkg/buildkit/buildkit.go
This log statement will have an associated `logKey` field and, hence, will be processed and shipped by vector. We're logging the stacktrace inside of the controller but I'm not sure there's a benefit to pushing it into the remote logs. Do you disagree @steved ?
=> Logs solve error within Buildkit client

pkg/buildkit/worker/pool.go, pkg/buildkit/worker/pool_test.go, scripts/development/01-setup-minikube.sh
Beta API supports older and new Kubernetes versions (>= 1.18) so this provides great cluster compatibility right now. We can migrate to v1 after the betav1 API is removed in a future version.
=> Uses discoveryv1beta1 EndpointSlices in buildkit worker pool

pkg/buildkit/buildkit.go
a new buildkit client does not verify its connection with a buildkitd
worker when first created so a garbage addr like "foo.bar:1234" will
not return an error. running a "list workers" operation like we do in
the statefulset readiness check for buildkit should solve this problem
and also guarantee that the TCP server has had time to set up its TLS
certificates.
retrying the operation with a backoff makes several attempts to
establish the connection before the client is returned to the caller
=> Adds ListWorkers check when building buildkit client

pkg/controller/start.go
the former method is less straightforward than this approach and did not
work because i did not pass the opt newrelic.ConfigFromEnvironment()
=> Applies newrelic labels when starting APM

deployments/helm/hephaestus/templates/_helpers.tpl
The usage of `renderPullSecrets` is different than `pullSecrets`, but the usage here was for the latter not the former.
renderPullSecrets:
https://github.com/bitnami/charts/blob/dfffe74c212a28e27f537dbee54c3b5a81c7d572/bitnami/common/templates/_images.tpl#L51
pullSecrets:
https://github.com/bitnami/charts/blob/dfffe74c212a28e27f537dbee54c3b5a81c7d572/bitnami/common/templates/_images.tpl#L24
```
$ helm template . --set "global.imagePullSecrets[0]=domino-quay-repos" | grep -A1 imagePullSecrets
[nil]
$ helm template . --set "global.imagePullSecrets[0]=domino-quay-repos" | grep -A1 imagePullSecrets
imagePullSecrets:
- name: domino-quay-repos
--
imagePullSecrets:
- name: domino-quay-repos
--
imagePullSecrets:
- name: domino-quay-repos
--
imagePullSecrets:
- name: domino-quay-repos
```
=> helm chart: fix image pull secrets rendering

deployments/helm/hephaestus/templates/buildkit/configmap.yaml, deployments/helm/hephaestus/templates/controller/secret.yaml, deployments/helm/hephaestus/values.yaml, pkg/config/config.go, pkg/controller/imagebuild/component/builddispatcher.go, pkg/controller/support/credentials/credentials.go
In Forge, we allowed setting of insecure registries [on the objects themselves](https://github.com/dominodatalab/hephaestus/blob/747da51794616fe700c302e7c21c18a842e8159e/pkg/api/forge/v1alpha1/containerimagebuild_types.go#L64), which did not make it to Hephaestus.
Unfortunately, the only way to configure HTTP-only or insecure HTTPS registry hosts is [through the buildkitd.toml](https://github.com/moby/buildkit/issues/2044#issuecomment-811489932) config. This makes it impossible to set them per-image build and requires deploy-time configuration.
To support credential validation against HTTP-only or insecure registries, the info needs to be passed to the controller as well.
=> support configuration of insecure registries

.github/workflows/main.yml, Makefile, api/openapi-spec/swagger.json, build/README.md, build/buildkit/Dockerfile, prototype/openapiv3/config.yaml, prototype/openapiv3/main.go, scripts/sdk/generate.sh, scripts/sdk/kind.yaml, scripts/sdk/main.go, scripts/sdk/pom.xml, scripts/sdk/settings.xml
- Fixed time serialization bug that caused the `list/get` operations to fail
- Fixed token-based authentication by adding _bearer token_ auth strategy to client
- Pushes artifacts to artifactory for consumption by application engineers
=> Improves Java SDK generation

deployments/helm/hephaestus/templates/controller/deployment.yaml, deployments/helm/hephaestus/templates/controller/serviceaccount.yaml, deployments/helm/hephaestus/values.yaml
Creates configurations for both GCP and Azure in order to access GCR and ACR, respectively. ECR has not been added because we rely on the underlying IAM Role -> Instance Profile to provide credentials. Obviously, we can change and/or extend this as-needed in the future.
=> Add cloud-base registry configuration values to Helm chart

deployments/helm/hephaestus/templates/buildkit/statefulset.yaml
When `fsGroup` runs on an already-existing volume when buildkit is scaled back up it can materially change the GID of unpacked snapshots from container images that can cause future build failures.
=> only change buildkit fsGroup during mismatch or initial pod startup

.golangci.yml, pkg/controller/start.go, pkg/controller/support/credentials/cloudauth/acr/acr.go, pkg/controller/support/credentials/cloudauth/acr/acr_integration_test.go, pkg/controller/support/credentials/cloudauth/ecr/ecr.go, pkg/controller/support/credentials/cloudauth/gcr/gcr.go, pkg/controller/support/credentials/credentials.go
- passes ctx when registering providers
- checks for the presence of envvars to decide if ACR should be enabled; errors out if credentials are incomplete or incorrect
=> Makes ACR cloudauth messages more informative

pkg/buildkit/worker/pool.go, pkg/buildkit/worker/pool_test.go, scripts/development/01-setup-minikube.sh
The former has been removed in k8s 1.25 since we no longer need to support k8s < 1.21. _Mo' versions, mo' problems._
=> Moves from discoveryv1beta1 to discoveryv1 API for EndpointSlices

pkg/buildkit/worker/pool.go, pkg/buildkit/worker/pool_test.go
so that pending pods are afforded the same grace period as running pods before termination
=> Buildkit worker pool uses podMaxIdleTime for pending pods

deployments/helm/hephaestus/templates/crd-hooks.yaml, deployments/helm/hephaestus/values.yaml
adds `.Values.uninstallCRDs` to helm chart
by default, this chart will no longer uninstall the CRDs when the helm chart release is deleted. this will prevent the accidental deletion of CRs that might be needed and also, in the case of uninstall/re-install, keep k8s from losing its mind whenever the CRDs are removed and CRs are present. this latter case usually results in the k8s CP taking a few mins to figure out what's happening and stabilize.
=> Do not auto-delete CRDs on helm uninstall

deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/values.yaml
All charts must have a pod security context defined. It must include runAsNonRoot, runAsUser and seLinuxOption.
=> PLAT-5844: Explicit Pod Security Contexts

pkg/buildkit/worker/pool_test.go, pkg/buildkit/worker/scalearbiter.go
27c43734053bc3095972a0c83a5b1d2040bca0de contains the failing test case: a leased pod was removed when only the last expired pod should have been.
193bd27674903861e228c4bbfc484b4fe4c6648b contains a rework of the pool arbitration to ensure that no leased, pending, or running pods are scaled down. only above that minimum number of replicas can we prioritize recycling of expired/invalid pods over serving a new build request.
=> ensure that leased, pending, or running pods are never scaled down during pool reconciliation

deployments/helm/hephaestus/templates/buildkit/statefulset.yaml
When the CA repacks nodes due to underutilization (< 50% by default), it could do so in the middle of an active build. Prevent that by setting `safe-to-evict` to false. An alternative may be to apply this annotation during lease acquisition.
=> buildkit statefulset pods are not safe for the cluster-autoscaler to evict

build/buildkit/Dockerfile, deployments/helm/hephaestus/templates/buildkit/configmap.yaml, deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/values.yaml
Using other UIDs should not really be recommended, due to the custom image, but in the event that it's necessary (which one organization is speculating it may be for them), this will give some template to follow.
=> Helpers for using rootless with non-default UIDs

.github/actions/cloud-image-building/action.yml, .github/actions/push-docker-image/action.yml, .github/actions/vendor-docker-image/action.yml, .github/workflows/functional.yml, .github/workflows/main.yml, .github/workflows/security.yml, deployments/helm/hephaestus/templates/controller/cronjob.yaml, pkg/cmd/controller/root.go, pkg/controller/runGC.go, pkg/crd/crd.go, pkg/kubernetes/istio.go, test/functional/go.mod, test/functional/go.sum
To properly work with Istio, the cronjob must be able to wait for the proxy sidecar to start and then call `/quitquitquit` at exit.
=> cleanup cronjob must support istio during startup

deployments/helm/hephaestus/templates/_helpers.tpl, deployments/helm/hephaestus/templates/buildkit/configmap.yaml, deployments/helm/hephaestus/templates/buildkit/networkpolicy.yaml, deployments/helm/hephaestus/templates/buildkit/podsecuritypolicy.yaml, deployments/helm/hephaestus/templates/buildkit/service.yaml, deployments/helm/hephaestus/templates/buildkit/serviceaccount.yaml, deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/templates/certificates.yaml, deployments/helm/hephaestus/templates/controller/secret.yaml, deployments/helm/hephaestus/values.yaml
If the buildkit is in the same namespace as the controller, use Issuers instead of ClusterIssuers.
=> PLAT-6592: certificate issuer based on buildkit ns

pkg/controller/imagebuild/component/builddispatcher.go, pkg/controller/support/credentials/credentials.go, pkg/controller/support/credentials/credentials_test.go, test/functional/helpers_test.go
as we can't establish a definitive 1:1 correlation between the server field in registry auth and the computed docker config.json in downstream authentication, this adds a `helpMessage` str slice to store general metadata about the credentials supplied to an `imagebuild` that can be leveraged in any error message(s) related to failed registry authentication.
=> PLAT-5981: clarify error message when registry validation fails on an image build

pkg/buildkit/buildkit.go, pkg/controller/imagebuild/component/builddispatcher.go
=> PLAT-6911: Allow concurrent builds

deployments/helm/hephaestus/templates/buildkit/configmap.yaml
The error looked like this:
```
time="2023-07-17T19:20:12Z" level=warning msg="currently, only the default worker can be used."
time="2023-07-17T19:20:12Z" level=warning msg="TLS is disabled for unix:///run/user/%!s(float64=1000)/buildkit/buildkitd.sock"
buildkitd: mkdir /run/user/%!s(float64=1000): permission denied
[rootlesskit:child ] error: command [buildkitd --config /etc/buildkit/buildkitd.toml] exited: exit status 1
[rootlesskit:parent] error: child exited: exit status 1
```
Before:
```
$ helm template . -s templates/buildkit/configmap.yaml
[snip]
address = [ "tcp://0.0.0.0:1234", "unix:///run/user/%!s(float64=1000)/buildkit/buildkitd.sock" ]
$ helm template . -s templates/buildkit/configmap.yaml --set buildkit.rootlessUser=1234
[snip]
address = [ "tcp://0.0.0.0:1234", …
```
=> rootless causes invalid buildkitd mount path to be used

.github/workflows/main.yml, go.mod, pkg/controller/start.go, pkg/controller/support/credentials/cloudauth/ecr/ecr.go
In AWS, it can take longer than the default to register a client
because of IMDS. By setting a deadline, we override the default
timeout.  Adds debug logging to the AWS client.
Having a built-in env var for this is still pending: https://github.com/aws/aws-sdk-go/issues/3495.
=> add a deadline to cloud client registration

pkg/controller/support/credentials/cloudauth/ecr/ecr.go, pkg/controller/support/credentials/cloudauth/ecr/ecr_test.go
When accessing an ECR repo cross-region, we need to configure the ECR client with credentials from that region.
=> support cross-region ECR authentication

deployments/crds/hephaestus.dominodatalab.com_imagebuilds.yaml, deployments/crds/hephaestus.dominodatalab.com_imagecaches.yaml, pkg/api/hephaestus/v1/types.go, pkg/api/hephaestus/v1/validations.go, pkg/controller/support/credentials/credentials.go, test/functional/aks_test.go, test/functional/eks_test.go, test/functional/gke_test.go
Cloud provider specification isn't necessary as we can either take the explicit secrets being passed or use a regex to attempt a cloud login.
=> deprecate explicit cloud provider config for pull registries and retry credential verification

deployments/helm/hephaestus/templates/_helpers.tpl, deployments/helm/hephaestus/values.yaml
We currently default to the rootless buildkit image as the only image in the config, and then life-mutate the image tag to what we presume the non-rootless one would be based on a string substitution.
Let's just clearly define the two images and pick the appropriate one.
=> Define rootless/non-rootless image tags separately

.github/workflows/main.yml
The previous PR (#246) updated how the helm chart references the buildkit images, but our build process to vendor the buildkit images uses that chart's values, using the same string substitution separately, to determine the base image. This causes us to use the incorrect image when vendoring buildkit.
=> Update buildkit CI after buildkit helm chart image change

deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/values.yaml
The buildkit's container securityContext isn't configurable. Added variables for it for both the rootless and rootful (umm) modes.
=> PLAT-9281: Make securityContext for buildkit container configurable

deployments/helm/hephaestus/templates/buildkit/configmap.yaml, deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/values.yaml
- Even when subgid/subuid fixes are baked into the dockerfile, when launched as a pod the istio settings propagate to `/etc/subgid` and `/etc/subuid`. With this configmap update, the right setting (`user:100000:65536`) gets all the way to the container.
- Due to flag discrepancies between docker and containerd, per the [documented tip](https://github.com/moby/buildkit/blob/f8c19098c91a0cd4a2d9cd35e2b3c2a1c8b3f622/docs/rootless.md#change-uidgid) around security-opt flags, we set `--privileged` in rootless too
=> Rootless configs

deployments/helm/hephaestus/Chart.lock, deployments/helm/hephaestus/Chart.yaml, renovate.json
Our chart was actually built against this older version of the bitnami common chart. The reference was updated, but the code doesn't match it, doesn't work with it, and currently in production isn't using it. Downgrade the reference to the version we're actually using so that dep operations don't pull in a broken version.
The update was done by renovate, so I'm also disabling renovate managing helm dependencies. It's the only helm dependency in the repo.
=> Downgrade bitnami common version

deployments/helm/hephaestus/Chart.yaml, deployments/helm/hephaestus/templates/controller/deployment.yaml, deployments/helm/hephaestus/values.yaml
We have a customer who wants to access their google artifact registry from their domino cloud control plane, but because of the way hephaestus works, it will want to do cloud authorization to gcp with these images.
This PR provides a mechanism to setup that authorization to gcr:
```
kubectl -n domino-compute create secret generic gcp-service-account --from-file=key.json=/path/to/service-account/creds.json
[...]
release_overrides:
chart_values:
controller:
manager:
cloudRegistryAuth:
gcp:
mountedCredentials:
secretName: gcp-service-account
keyName: key.json
```
This will mount the google credentials into the hephaestus-manager pod, allowing it to auth for these images.
=> PLAT-9527: Add ability to define a secret with google creds

deployments/helm/hephaestus/templates/buildkit/statefulset.yaml, deployments/helm/hephaestus/values.yaml
Problem:
`hephaestus-buildkit` pods are experiencing cgroup-related probe failures that prevent them from becoming ready, despite the containers starting successfully. 
The liveness and readiness probes are failing with the error:
`rpc error: code = Unknown desc = command error: error opening file '/sys/fs/cgroup/kubepods.slice/kubepods-pod[UUID].slice/crio-[CONTAINER_ID].scope/cgroup.freeze: No such file or directory`
Running `buildctl debug workers` works inside buildkit containers, but is problematic as a probe. Testing the TCP socket is more reliable and not susceptible to cgroup v1/v2 differences as well as others with CRI-O, etc.
Changes:
- Set the `exec.command` to `null`
- Set `tcpSocket.port: 1234` (also set in the buildkit args)
- Adjusted test thresholds
=> PLAT-9268 - Switch to socket probe

.github/actions/push-multiple-container-images/action.yaml, .github/workflows/main.yml, pkg/controller/support/credentials/cloudauth/gcr/gcr.go, pkg/controller/support/credentials/cloudauth/gcr/gcr_test.go
Problem:
* Accessing at least one particular customer's `us.gcr.io` endpoint via injected service account credentials on a non-GKE cluster authenticates initially, but fails at pull time with a 401
* Building arm is slow as hell
* sha tag for debug was overwriting the non-debug one (or vice versa, it's a race)
Changes:
* Remove `registrytoken` from gcp auth method
* Our GCR/GAR support gets a bearer token and supplies it in the registrytoken field
* It seems that with this account in particular, the bearer token we have does not function
* It does work with our own AR 
* I suspect it's not scoped to the image registry or paths we're working with
* However, I don't think there's any point in propagating this. Buildkit can handle it just fine with the oauth token.
* Run a separate arm build …
=> PLAT-9527: Don't use the registry token in gcr
